#pragma once

struct weaponids_t
{
	void init();
	uint32_t get( uint32_t name );

	std::unordered_map<uint32_t, uint32_t> m_weaponids = {};

	uint32_t weapon_deagle;
	uint32_t weapon_elite;
	uint32_t weapon_fiveseven;
	uint32_t weapon_glock;
	uint32_t weapon_ak47;
	uint32_t weapon_aug;
	uint32_t weapon_awp;
	uint32_t weapon_famas;
	uint32_t weapon_g3sg1;
	uint32_t weapon_galilar;
	uint32_t weapon_m249;
	uint32_t weapon_m4a1;
	uint32_t weapon_mac10;
	uint32_t weapon_p90;
	uint32_t weapon_mp5sd;
	uint32_t weapon_ump45;
	uint32_t weapon_xm1014;
	uint32_t weapon_bizon;
	uint32_t weapon_mag7;
	uint32_t weapon_negev;
	uint32_t weapon_sawedoff;
	uint32_t weapon_tec9;
	uint32_t weapon_taser;
	uint32_t weapon_hkp2000;
	uint32_t weapon_mp7;
	uint32_t weapon_mp9;
	uint32_t weapon_nova;
	uint32_t weapon_p250;
	uint32_t weapon_scar20;
	uint32_t weapon_sg556;
	uint32_t weapon_ssg08;
	uint32_t weapon_knifegg;
	uint32_t weapon_knife;
	uint32_t weapon_flashbang;
	uint32_t weapon_hegrenade;
	uint32_t weapon_smokegrenade;
	uint32_t weapon_molotov;
	uint32_t weapon_decoy;
	uint32_t weapon_incgrenade;
	uint32_t weapon_c4;
	uint32_t weapon_healthshot;
	uint32_t weapon_knife_t;
	uint32_t weapon_m4a1_silencer;
	uint32_t weapon_usp_silencer;
	uint32_t weapon_cz75a;
	uint32_t weapon_revolver;
	uint32_t weapon_tagrenade;
	uint32_t weapon_fists;
	uint32_t weapon_breachcharge;
	uint32_t weapon_tablet;
	uint32_t weapon_melee;
	uint32_t weapon_axe;
	uint32_t weapon_hammer;
	uint32_t weapon_spanner;
	uint32_t weapon_knife_ghost;
	uint32_t weapon_firebomb;
	uint32_t weapon_diversion;
	uint32_t weapon_frag_grenade;
	uint32_t weapon_snowball;
	uint32_t weapon_bumpmine;
	uint32_t weapon_bayonet;
	uint32_t weapon_knife_flip;
	uint32_t weapon_knife_gut;
	uint32_t weapon_knife_karambit;
	uint32_t weapon_knife_m9_bayonet;
	uint32_t weapon_knife_tactical;
	uint32_t weapon_knife_falchion;
	uint32_t weapon_knife_survival_bowie;
	uint32_t weapon_knife_butterfly;
	uint32_t weapon_knife_push;
	uint32_t weapon_knife_ursus;
	uint32_t weapon_knife_gypsy_jackknife;
	uint32_t weapon_knife_stiletto;
	uint32_t weapon_knife_widowmaker;
	uint32_t studded_bloodhound_gloves;
	uint32_t t_gloves;
	uint32_t ct_gloves;
	uint32_t sporty_gloves;
	uint32_t slick_gloves;
	uint32_t leather_handwraps;
	uint32_t motorcycle_gloves;
	uint32_t specialist_gloves;
};

extern weaponids_t weaponids;